"""Edit table columns

Revision ID: 4c0f76d84e9b
Revises: 90e20c1cfdb3
Create Date: 2024-01-04 07:52:27.864730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0f76d84e9b'
down_revision: Union[str, None] = '90e20c1cfdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
